/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "ConnectNotify": {
      "name": string
      "type": "sst.aws.Function"
    }
    "MusicAuth": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
    "MusicData": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "MusicWebClient": {
      "id": string
      "secret": string
      "type": "sst.aws.CognitoUserPoolClient"
    }
    "PortaputerInstallers": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Portfolio": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "ScheduleCall": {
      "name": string
      "type": "sst.aws.Function"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}